name: flutter_functional_widget
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.6.0-36.0.dev
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  macros: ^0.1.0-main.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
